### ISSUE TITLE
Maps: use labels instead of tooltips

### ISSUE THREAD

**Issue by timwis** [CodeForPhilly/philly-ward-leaders#148]
A fellow in Leaflet's gitter showed me how he's used `L.tooltip` for labels:

![2017-09-25-13_03_19-index html](https://user-images.githubusercontent.com/761444/30858719-d322ce4e-a28e-11e7-82b1-7850b5f028a6.png)

Tooltip options:
```js
{permanent: true}
```

And styles:
```css
.leaflet-tooltip {
    background: none;
    box-shadow: none;
    border: none;
}
.leaflet-tooltip-left:before, .leaflet-tooltip-right:before {
    border: 0px;
}
```

And to prevent overlapping labels, we can use [Geovation/labelgun](https://github.com/Geovation/labelgun). Woot!
